services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Guave\AssetLoadBundle\:
    resource: ../../../src
    exclude: ../../../src/{Entity,Migrations,Model,Resources,Tests,Widget}

  Guave\AssetLoadBundle\Controller\:
    resource: ../../../src/Controller
    public: true

  Guave\AssetLoadBundle\Twig\AssetLoadExtension:
    tags:
      - { name: twig.extension }

  Guave\AssetLoadBundle\Twig\TwigTemplateExtension:
    arguments:
      - '@contao.twig.filesystem_loader'
    tags:
      - { name: twig.extension }
