services:
  _defaults:
    autoconfigure: true
    autowire: true

  Guave\AssetLoadBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection}

  Guave\AssetLoadBundle\Twig\:
    resource: ../src/Twig
    tags:
      - { name: twig.extension }

  Guave\AssetLoadBundle\Twig\TwigTemplateExtension:
    arguments:
      - '@contao.twig.filesystem_loader'
