services:
  _defaults:
    autoconfigure: true

  Guave\AssetLoadBundle\Twig\AssetLoadExtension:
    tags:
      - { name: twig.extension }

  Guave\AssetLoadBundle\Twig\TwigTemplateExtension:
    arguments:
      - '@contao.twig.filesystem_loader'
    tags:
      - { name: twig.extension }
